### PR TITLE
DOC : audio.py, mouse.py, state.py, keyboard.py

### PR DESCRIPTION
**Pull request by beegica**
Changed the docstrings to reference the most resent parent class with a new logged attribute.

### CODE REVIEW

**Comment by beegica** [comment]
But Wait has a "relevant" logged attribute. I would think it makes more sense to have KeyState point to wait, and then wait point to state, that way on the way up the chain they see all of the logged attributes that are available to KeyPress. Does that make sense? If not Ill switch all of them up to point to check out state if they are a subclass of state

**Comment by psederberg** [comment]
What is that relevant logged attribute? I think I'm just missing it.

**Comment by beegica** [comment]
event_time and until_value

**Comment by beegica** [comment]
Im not sure if they are relevant to a KeyPress state, but they exist.

**Comment by beegica** [comment]
I guess since you dont pass anything into an *until* argument for KeyPress, until_value isnt relevant. *event_time* could be relevant to someone though.

**Comment by beegica** [comment]
Scratch that, *event_time* is only relevant in the case of an until, As *event_time* is the time at which the until was evaluated as true.

**Comment by beegica** [comment]
First pass complete!

**Comment by psederberg** [comment]
There are a handful of indentation issues that need fixing before I can
merge it in. I can show you tomorrow, but if you compare this to how they
are in other places you should see how they need to be fixed up. Also, they
currently prevent smile from running.

**Pull request merged**
