### PR TITLE
ADD: Added flip every frame functionallity to idle_callback

### PR DESCRIPTION
**Pull request by beegica**

### CODE REVIEW

**Comment by psederberg** [comment]
It seems like you never make use of FLIP_TIME_MIN or self.estimated_last_flip. 

Can you take a pass to clean it all up where you can and also provide an outline in the comments here (or on slack) for what your changes are doing?

**Comment by beegica** [comment]
Looks like a couple of those were held over from testing our the calc_flip_interval. Ill do a pull fixing those. 

116 : initialized self._did_draw to false. This is a test for whether or not we have already drawn for this flip. If something is scheduled after we draw but before we flip (Might not be possible) I wanted to make sure that it wouldn't try to draw it since we already decided to non_blocking flip.

139-142 : Setting up the new idle variables. self.last_blocking_flip is used to calculate the time in which we think the next flip should happen. The equation we use is *next_flip_time = last_blocking_flip + flip_interval * flips_after_blocking_flip*.

158-160 : just calculating the new next_flip_time on a resize

305 - 312 : I needed to add another condition for redrawing the screen. I want to redraw if we haven't called draw yet AND we are within flip_time_margin of the next flip time. 

339 - 340 : I needed to add the same conditional for redrawing as flipping. Since we are flipping and reseting the value of did_draw, we dont need to include that in our conditional. 

352 - 359 : Recalculating the next flip time for blocking flips

362 - 372 : Recalculating the next flip time for non-blocking flips

384 : resetting _did_draw to false

**Comment by psederberg** [comment]
I think variables like last_blocking_flip, next_flip_time, etc... (there are a few you've added), should all be prefaced with an underscore since they are not public attributes of the class. So it should be self._last_blocking_flip...

**Comment by psederberg** [comment]
Following up on our conversation from today:

1) On lines 306-307, this will flip for kivy_needs_draw, even if we've drawn already. I think this is likely correct, but if it's not, then we need to keep track that kivy needed a draw so that it can happen on the next flip. 

2) Is the variable within_flip_time_margin correctly named? Is that what it really is in order to determine whether to draw?

**Comment by beegica** [comment]
within_redraw_window might actually be better. 

As for lines 306&307, So it turns out that within_flip_time_margin and ready_for_video are essentially the same calculation. I might be able to just replace within_flip_time_margin with ready for video.

**Comment by beegica** [comment]
Okay They are the exact same thing. I am going to do some testing with just ready for video.

**Comment by beegica** [comment]
My concerns weren't warranted, unfortunately. The only thing that is weird is that  

(self._new_time - self._last_kivy_tick >= self.flip_interval)

will only be true during non-blocking flips, which I think is actually what we want.

**Comment by beegica** [comment]
I also don't think that there will be a problem with lines 306-307

**Comment by psederberg** [comment]
A separate merge fixed this issue.

**Pull request closed without merging**
