### PR TITLE
BF : Mathdistract only producing 1 list of questions in a loop

### PR DESCRIPTION
**Pull request by beegica**

### CODE REVIEW

**Comment by psederberg** [comment]
Do you have to instantiate that function inside the subroutine or can it be pulled out? I'm fine if there's a reason you're doing it inside, I just thought I'd ask.

**Comment by beegica** [comment]
It can be pulled out. Probably the best idea. Ill change it

**Comment by psederberg** [comment]
If you do, you might want to name it with a preceding underscore, so it's
not a top-level method when people import it.

**Comment by psederberg** [comment]
Looks like there's still a Debug in there. Can you take a new pass to see whether this is up to your current coding standards? Also, does this include the minor fix Brian had (I can't remember what it was)?

**Comment by psederberg** [comment]
Can you double-check this PR to make sure it's still ready. I think the previous comment is still relevant.

**Comment by dyld-w** [comment]
Closing without merging as we already have `math_distract.py` in the project which has been updated more recently.

**Pull request closed without merging**
