### PR TITLE
DOCS: Breakup

### PR DESCRIPTION
**Pull request by beegica**
DOCS: Action state examples, 
DOCS: Links between documents, 
DOCS: inline linking of smile stuff,
DOCS: Add image and finish index.rst

### CODE REVIEW

**Comment by psederberg** [comment]
I think you might want to move the smile_example.png into the _static directory. I think that's how sphinx wants you to do things so they deploy properly.

**Comment by beegica** [comment]
Okay I moved the image over

**Comment by psederberg** [comment]
Did you recompile to make sure it shows the image on the start page? I would think you need to reference it in _static in the index.rst file.

**Comment by beegica** [comment]
Okay pull this one, Then pull in real_examples.

**Pull request merged**
