### PR TITLE
ADD: Changed questionnaire example.

### PR DESCRIPTION
**Pull request by beegica**

### CODE REVIEW

**Comment by psederberg** [comment]
Can you also remove the yo-yo.csv? Or is that already removed?

On Jul 21, 2016 1:05 PM, "beegica" <notifications@github.com> wrote:

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/compmem/smile/pull/83
Commit Summary

   - ADD: Changed questionnaire example.

File Changes

   - *A* docs/examples/questionnaire_example.csv
   <https://github.com/compmem/smile/pull/83/files#diff-0> (26)
   - *A* docs/examples/questionnaire_test.py
   <https://github.com/compmem/smile/pull/83/files#diff-1> (12)
   - *M* smile/questionnaire.py
   <https://github.com/compmem/smile/pull/83/files#diff-2> (82)

Patch Links:

   - https://github.com/compmem/smile/pull/83.patch
   - https://github.com/compmem/smile/pull/83.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/compmem/smile/pull/83>, or mute the thread

**Comment by beegica** [comment]
Done!

**Comment by psederberg** [comment]
And is the example at the bottom of the file inside a name main clause? And
updated to work based on a list of dicts, not a CSV? (Sorry, not at my
computer to check easily).

**Comment by beegica** [comment]
Yuppers!

**Pull request merged**
