### PR TITLE
Smile doc strings

### PR DESCRIPTION
**Pull request by beegica**
MF : Audio.py Docstrings
MF : Experiment.py Docstrings
MF : keyboard.py docstrings
MF : log.py docstrings
MF : mouse.py docstrings
MF : pulse.py docstrings
MF : ref.py docstrings
MF : state.py docstrings

### CODE REVIEW

**Comment by psederberg** [comment]
I don't know if this will be easy to do, but it might be nice to make the docstrings a separate PR from the general docs PR. It will make it easier to resolve tweaks.

**Comment by psederberg** [comment]
Also, I found some errors, such as:

```
Log('name':'Loop',
        'correct':kp.correct,
        'time_to_respond':kp.rp
        ) 
```

You probably want `=` instead of `:`.

**Comment by psederberg** [comment]
Can you also change out the camelCase to instead follow PEP8: https://www.python.org/dev/peps/pep-0008/

This is just so we can follow consistent python naming conventions both in code and in our examples. So, variable names will go from `maxResponseTime` to `max_response_time`.

**Comment by psederberg** [comment]
The docstrings themselves are looking good, but here are some things to fix up:

1) You need a one-liner at the top describing in a few words what the state does, e.g., "Play a beep for the specified duration and frequency." Then you have a line break before launching into the longer description.

2) When you list the log attrs you don't need to relist the command args of the function (e.g., you don't have to put `fadein` for both Parameters and the Logged Attributes.

**Comment by psederberg** [comment]
Things like `MouseWithin` are not developer only. They are easy shortcuts for people to do things like wait until the mouse is within a widget and stuff like that.

**Comment by beegica** [comment]
yeah those general docs shouldn't be in this pull request. It should have been just a branch from smile-kivy. Ill fix it.

**Comment by beegica** [comment]
Is it okay if I close this pull request, I dont know what happened but I fixed it.

**Comment by psederberg** [comment]
sure.

**Pull request closed without merging**
