### PR TITLE
New user docs

### PR DESCRIPTION
**Pull request by beegica**
AF : Sphinx's needed files
AF : Sphinx theme Pyramid
AF : install.rst
AF : getting_started.rst
AF : android.rst
AF : listpresent.py
AF : main.py
AF : main_list_present.py
AF : rand_word_1.py
AF : rand_word_2.py
AF : smile.rst
AF : tutorial.rst

DOCS : PEP8 Compliance 

AF: accessing_data.rst

### CODE REVIEW

**Comment by psederberg** [comment]
Are you sure we need all those files for the read the docs template? Isn't this part of the sphinx install somewhere so we don't need it here?

**Comment by beegica** [comment]
All of the files are part of the read_the_docs template, so I am pretty sure we need most of them.

**Comment by psederberg** [comment]
But do we need to include the read_the_docs template in our code? Is that
template not included in sphinx?

**Comment by beegica** [comment]
The ReadTheDocs theme doesn't come with sphinx, we have to include it if we want the end user to be able to *make html* or *make pdf*

**Comment by psederberg** [comment]
I think it's fair to make it a requirement that folks install it into their
own sphinx install to compile the docs. From what I can tell, I haven't
been able to find a single python project that includes the sphinx
templates.

**Pull request closed without merging**
